export enum Story {
  A_STUDY_IN_SCARLET = 'A Study in Scarlet',
  THE_SIGN_OF_THE_FOUR = 'The Sign of the Four',

  A_SCANDAL_IN_BOHEMIA = 'A Scandal in Bohemia',
  THE_RED_HEADED_LEAGUE = 'The Red-Headed League',
  A_CASE_OF_IDENTITY = 'A Case of Identity',
  THE_BOSCOMBE_VALLEY_MYSTERY = 'The Boscombe Valley Mystery',
  THE_FIVE_ORANGE_PIPS = 'The Five Orange Pips',
  THE_MAN_WITH_THE_TWISTED_LIP = 'The Man with the Twisted Lip',
  THE_ADVENTURE_OF_THE_BLUE_CARBUNCLE = 'The Adventure of the Blue Carbuncle',
  THE_ADVENTURE_OF_THE_SPECKLED_BAND = 'The Adventure of the Speckled Band',
  THE_ADVENTURE_OF_THE_ENGINEERS_THUMB = 'The Adventure of the Engineer’s Thumb',
  THE_ADVENTURE_OF_THE_NOBLE_BACHELOR = 'The Adventure of the Noble Bachelor',
  THE_ADVENTURE_OF_THE_BERYL_CORONET = 'The Adventure of the Beryl Coronet',
  THE_ADVENTURE_OF_THE_COPPER_BEECHES = 'The Adventure of the Copper Beeches',

  SILVER_BLAZE = 'Silver Blaze',
  THE_YELLOW_FACE = 'The Yellow Face',
  THE_STOCK_BROKERS_CLERK = 'The Stock-Broker’s Clerk',
  THE_GLORIA_SCOTT = 'The “Gloria Scott”',
  THE_MUSGRAVE_RITUAL = 'The Musgrave Ritual',
  THE_REIGATE_SQUIRES = 'The Reigate Squires',
  THE_CROOKED_MAN = 'The Crooked Man',
  THE_RESIDENT_PATIENT = 'The Resident Patient',
  THE_GREEK_INTERPRETER = 'The Greek Interpreter',
  THE_NAVAL_TREATY = 'The Naval Treaty',
  THE_FINAL_PROBLEM = 'The Final Problem',

  THE_ADVENTURE_OF_THE_EMPTY_HOUSE = 'The Adventure of the Empty House',
  THE_ADVENTURE_OF_THE_NORWOOD_BUILDER = 'The Adventure of the Norwood Builder',
  THE_ADVENTURE_OF_THE_DANCING_MEN = 'The Adventure of the Dancing Men',
  THE_ADVENTURE_OF_THE_SOLITARY_CYCLIST = 'The Adventure of the Solitary Cyclist',
  THE_ADVENTURE_OF_THE_PRIORY_SCHOOL = 'The Adventure of the Priory School',
  THE_ADVENTURE_OF_BLACK_PETER = 'The Adventure of Black Peter',
  THE_ADVENTURE_OF_CHARLES_AUGUSTUS_MILVERTON = 'The Adventure of Charles Augustus Milverton',
  THE_ADVENTURE_OF_THE_SIX_NAPOLEONS = 'The Adventure of the Six Napoleons',
  THE_ADVENTURE_OF_THE_THREE_STUDENTS = 'The Adventure of the Three Students',
  THE_ADVENTURE_OF_THE_GOLDEN_PINCE_NEZ = 'The Adventure of the Golden Pince-Nez',
  THE_ADVENTURE_OF_THE_MISSING_THREE_QUARTER = 'The Adventure of the Missing Three-Quarter',
  THE_ADVENTURE_OF_THE_ABBEY_GRANGE = 'The Adventure of the Abbey Grange',
  THE_ADVENTURE_OF_THE_SECOND_STAIN = 'The Adventure of the Second Stain',

  THE_HOUND_OF_THE_BASKERVILLES = 'The Hound of the Baskervilles',
  THE_VALLEY_OF_FEAR = 'The Valley of Fear',

  THE_ADVENTURE_OF_WISTERIA_LODGE = 'The Adventure of Wisteria Lodge',
  THE_ADVENTURE_OF_THE_CARDBOARD_BOX = 'The Adventure of the Cardboard Box',
  THE_ADVENTURE_OF_THE_RED_CIRCLE = 'The Adventure of the Red Circle',
  THE_ADVENTURE_OF_THE_BRUCE_PARTINGTON_PLANS = 'The Adventure of the Bruce-Partington Plans',
  THE_ADVENTURE_OF_THE_DYING_DETECTIVE = 'The Adventure of the Dying Detective',
  THE_DISAPPEARANCE_OF_LADY_FRANCES_CARFAX = 'The Disappearance of Lady Frances Carfax',
  THE_ADVENTURE_OF_THE_DEVILS_FOOT = 'The Adventure of the Devil’s Foot',
  HIS_LAST_BOW = 'His Last Bow',

  THE_ILLUSTRIOUS_CLIENT = 'The Illustrious Client',
  THE_BLANCHED_SOLDIER = 'The Blanched Soldier',
  THE_ADVENTURE_OF_THE_MAZARIN_STONE = 'The Adventure of the Mazarin Stone',
  THE_ADVENTURE_OF_THE_THREE_GABLES = 'The Adventure of the Three Gables',
  THE_ADVENTURE_OF_THE_SUSSEX_VAMPIRE = 'The Adventure of the Sussex Vampire ',
  THE_ADVENTURE_OF_THE_THREE_GARRIDEBS = 'The Adventure of the Three Garridebs',
  THE_PROBLEM_OF_THOR_BRIDGE = 'The Problem of Thor Bridge',
  THE_ADVENTURE_OF_THE_CREEPING_MAN = 'The Adventure of the Creeping Man',
  THE_ADVENTURE_OF_THE_LIONS_MANE = 'The Adventure of the Lion’s Mane',
  THE_ADVENTURE_OF_THE_VEILED_LODGER = 'The Adventure of the Veiled Lodger',
  THE_ADVENTURE_OF_SHOSCOMBE_OLD_PLACE = 'The Adventure of Shoscombe Old Place',
  THE_ADVENTURE_OF_THE_RETIRED_COLOURMAN = 'The Adventure of the Retired Colourman',
}
